### PR TITLE
Updated Omnibus with RPM dist tag fixes

### PR DESCRIPTION
**Pull request by schisamo**
This PR brings in an updated RPM packager which adds a Fedora [Dist Tag](http://fedoraproject.org/wiki/Packaging:DistTag) (.e.g. `.el5`, `.el6`, `.el7` etc.) to the package name and spec's [Release Tag](http://fedoraproject.org/wiki/Packaging:NamingGuidelines#Release_Tag). This ensures the RPMs more closely match the Fedora packaging guidelines which many users and tools depend on.

Passing CI job:
http://wilson.ci.chef.co/job/opscode-push-jobs-server-trigger-ad_hoc/42/downstreambuildview/

/cc @chef/ociv @manderson26

### CODE REVIEW

**Comment by schisamo** [comment]
CI build is failing but it appears to be failing the same on the nightly builds of the master branch.

**Comment by manderson26** [comment]
Build stuff should be fixed by #76; I'm chasing down a few pedant errors right now.

**Comment by manderson26** [comment]
:+1: 
If the current CI run passes (http://wilson.ci.chef.co/job/opscode-push-jobs-server-trigger-git_poll/18) this should be good to go; rebase and merge away.

**Comment by schisamo** [comment]
OK CI is now passing: http://wilson.ci.chef.co/job/opscode-push-jobs-server-trigger-ad_hoc/42/downstreambuildview/

**Pull request merged**
