### PR TITLE
[JEX-169] Update enterprise cookbook version for systemd support on ubuntu

### PR DESCRIPTION
**Pull request by yzl**
Green pipeline run in my dev jenkins cluster:  http://10.194.10.88/job/opscode-push-jobs-server-trigger-ad_hoc/2/downstreambuildview/

### CODE REVIEW

**Comment by mmzyk** [comment]
@yl What's the enterprise name attribute for? I'm surprised that needs to be set, given that value you set appears to also be the default value.

**Comment by yzl** [comment]
@mmzyk I set the enterprise name attribute explicitly because the service wouldn't start until I did.  I took what looked to me like the direct path, but there may be a better way to accomplish the same thing.

**Comment by mmzyk** [comment]
I looked into this some more. I was thinking this was a special case and thought it was odd, but we set this attribute in other places this cookbook is used as well. This could all probably use a refactor, but that's for another day. I'm +1, @yzl

**Comment by manderson26** [comment]
👍 This seems reasonable to me (now that I know what it does).

**Pull request merged**
